=== sulu/sulu/src/Sulu/Component/Webspace/Loader/schema/webspace/webspace-1.1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           targetNamespace="http://schemas.sulu.io/webspace/webspace" xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:webspace="http://schemas.sulu.io/webspace/webspace"
           xmlns="http://schemas.sulu.io/webspace/webspace">
    <xs:complexType name="webspaceType">
        <xs:sequence>
            <xs:element type="xs:string" name="name"/>
            <xs:element name="key">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[a-z0-9_-]+"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element type="security" name="security" minOccurs="0" maxOccurs="1"/>
            <xs:element type="localizationsType" name="localizations"/>
            <xs:element type="segmentsType" name="segments" maxOccurs="1" minOccurs="0"/>
            <xs:element type="xs:string" name="theme" minOccurs="0" maxOccurs="1"/>
            <xs:element type="defaultTemplatesType" name="default-templates" minOccurs="1" maxOccurs="1"/>
            <xs:element type="templatesType" name="templates" minOccurs="0" maxOccurs="1"/>
            <xs:element type="navigationType" name="navigation"/>
            <xs:element type="resource-locatorType" name="resource-locator" maxOccurs="1" minOccurs="0"/>
            <xs:element type="portalsType" name="portals"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="security">
        <xs:sequence>
            <xs:element type="xs:string" name="system" maxOccurs="1" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="localizationsType">
        <xs:sequence>
            <xs:element type="localizationType" name="localization" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="localizationType" mixed="true">
        <xs:sequence>
            <xs:element type="localizationType" name="localization" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="language" use="required"/>
        <xs:attribute type="xs:string" name="country" use="optional"/>
        <xs:attribute type="xs:boolean" name="default" use="optional"/>
        <xs:attribute type="xs:boolean" name="x-default" use="optional"/>
        <xs:attribute name="shadow" use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="auto"/>
                    <xs:enumeration value="none"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="segmentsType">
        <xs:sequence>
            <xs:element type="segmentType" name="segment" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="segmentType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="key" use="optional"/>
                <xs:attribute type="xs:boolean" name="default" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="navigationType">
        <xs:sequence>
            <xs:element type="navigationContextsType" name="contexts" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="navigationContextsType">
        <xs:sequence>
            <xs:element type="navigationContextType" name="context" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="navigationContextType">
        <xs:sequence>
            <xs:element name="meta">
                <xs:complexType>
                    <xs:choice maxOccurs="unbounded">
                        <xs:element type="langType" name="title"/>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
        </xs:sequence>

        <xs:attribute name="key" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="langType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="lang" use="required" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="resource-locatorType">
        <xs:sequence>
            <xs:element type="xs:string" name="strategy"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="portalsType">
        <xs:sequence>
            <xs:element type="portalType" name="portal" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="portalType">
        <xs:sequence>
            <xs:element type="xs:string" name="name"/>
            <xs:element type="xs:string" name="key"/>
            <xs:element type="localizationsType" name="localizations" minOccurs="0" maxOccurs="1"/>
            <xs:element type="environmentsType" name="environments"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="defaultTemplatesType">
        <xs:sequence>
            <xs:element type="defaultTemplateType" name="default-template" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="defaultTemplateType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="type" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="templatesType">
        <xs:sequence>
            <xs:element type="templateType" name="template" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="templateType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="type" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="environmentsType">
        <xs:sequence>
            <xs:element type="environmentType" name="environment" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="environmentType">
        <xs:sequence>
            <xs:element type="urlsType" name="urls"/>
            <xs:element type="customUrlsType" name="custom-urls" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="type" use="optional"/>
    </xs:complexType>
    <xs:complexType name="urlsType">
        <xs:sequence>
            <xs:element type="urlType" name="url" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="urlType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="language" use="optional"/>
                <xs:attribute type="xs:string" name="country" use="optional"/>
                <xs:attribute type="xs:string" name="segment" use="optional"/>
                <xs:attribute type="xs:string" name="redirect" use="optional"/>
                <xs:attribute type="xs:boolean" name="main" use="optional"/>
                <xs:attribute type="xs:string" name="analytics-key" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="customUrlsType">
        <xs:sequence>
            <xs:element type="xs:string" name="custom-url" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="webspace" type="webspaceType">
        <xs:unique name="uniqueTemplateTypes">
            <xs:selector xpath="./webspace:templates/webspace:template"/>
            <xs:field xpath="@type"/>
        </xs:unique>
    </xs:element>
</xs:schema>

=== sulu/sulu/tests/Resources/DataFixtures/Webspace/valid/sulu.io_no_strategy.xml
<?xml version="1.0" encoding="utf-8"?>
<webspace xmlns="http://schemas.sulu.io/webspace/webspace"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://schemas.sulu.io/webspace/webspace http://schemas.sulu.io/webspace/webspace-1.1.xsd">

    <name>Sulu CMF</name>
    <key>sulu_io</key>

    <security>
        <system>sulu_io</system>
    </security>

    <localizations>
        <localization language="en" country="us" shadow="auto"/>
        <localization language="de" country="at" default="true"/>
    </localizations>

    <theme>sulu</theme>

    <default-templates>
        <default-template type="page">default</default-template>
        <default-template type="homepage">overview</default-template>
    </default-templates>

    <navigation>
        <contexts>
            <context key="main">
                <meta>
                    <title lang="de">Hauptnavigation</title>
                    <title lang="en">Mainnavigation</title>
                </meta>
            </context>
            <context key="footer">
                <meta>
                    <title lang="de">Unten</title>
                    <title lang="en">Footer</title>
                </meta>
            </context>
        </contexts>
    </navigation>

    <portals>
        <portal>
            <name>Sulu CMF AT</name>
            <key>sulucmf_at</key>

            <localizations>
                <localization language="en" country="us"/>
                <localization language="de" country="at" default="true"/>
            </localizations>

            <environments>
                <environment type="prod">
                    <urls>
                        <url language="de" country="at">sulu.at</url>
                        <url redirect="sulu.at">www.sulu.at</url>
                    </urls>
                </environment>
                <environment type="dev">
                    <urls>
                        <url language="de" country="at">sulu.lo</url>
                    </urls>
                </environment>
                <environment type="main">
                    <urls>
                        <url language="de" country="at">sulu.lo</url>
                        <url language="de" country="at" main="true">sulu.at</url>
                        <url language="de" country="at">at.sulu.de</url>
                    </urls>
                </environment>
            </environments>
        </portal>
    </portals>
</webspace>

=== sulu/sulu/src/Sulu/Bundle/ContentBundle/Tests/Application/config/webspaces/sulu.io.xml
<?xml version="1.0" encoding="utf-8"?>
<webspace xmlns="http://schemas.sulu.io/webspace/webspace"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/webspace/webspace http://schemas.sulu.io/webspace/webspace-1.1.xsd">

    <name>Sulu CMF</name>
    <key>sulu_io</key>

    <localizations>
        <localization language="en" shadow="auto">
            <localization language="en" country="us" shadow="auto"/>
        </localization>
        <localization language="fr"/>
        <localization language="de">
            <localization language="de" country="at"/>
        </localization>
    </localizations>

    <theme>default</theme>

    <default-templates>
        <default-template type="page">default</default-template>
        <default-template type="homepage">overview</default-template>
    </default-templates>

    <navigation>
        <contexts>
            <context key="main">
                <meta>
                    <title lang="en">Mainnavigation</title>
                </meta>
            </context>
            <context key="footer">
                <meta>
                    <title lang="en">Footernavigation</title>
                </meta>
            </context>
        </contexts>
    </navigation>

    <resource-locator>
        <strategy>tree_leaf_edit</strategy>
    </resource-locator>
    
    <portals>
        <portal>
            <name>Sulu CMF AT</name>
            <key>sulucmf_at</key>

            <localizations>
                <localization language="fr"/>
                <localization language="de" country="at" default="true"/>
                <localization language="de"/>
                <localization language="en"/>
                <localization language="en" country="us"/>
            </localizations>

            <environments>
                <environment type="prod">
                    <urls>
                        <url language="de" country="at">sulu.at</url>
                        <url redirect="sulu.at">www.sulu.at</url>
                    </urls>
                </environment>
                <environment type="dev">
                    <urls>
                        <url language="de" country="at">sulu.lo</url>
                        <url language="de" country="at">localhost</url>
                        <url redirect="sulu.lo">sulu-redirect.lo</url>
                    </urls>
                </environment>
                <environment type="phpcr">
                    <urls>
                        <url language="de" country="at">sulu.lo</url>
                        <url language="de" country="at">localhost</url>
                        <url redirect="sulu.lo">sulu-redirect.lo</url>
                    </urls>
                </environment>
                <environment type="test">
                    <urls>
                        <url language="de" country="at">sulu.lo</url>
                        <url language="de" country="at">localhost</url>
                        <url redirect="sulu.lo">sulu-redirect.lo</url>
                    </urls>
                </environment>
            </environments>
        </portal>
    </portals>
</webspace>

=== sulu/sulu/config/webspaces/sulu-blog.xml
<?xml version="1.0" encoding="utf-8"?>
<webspace xmlns="http://schemas.sulu.io/webspace/webspace"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/webspace/webspace http://schemas.sulu.io/webspace/webspace-1.1.xsd">
    <name>Sulu Blog</name>
    <key>sulu-blog</key>

    <security>
        <system>Sulu Blog</system>
    </security>

    <localizations>
        <localization language="en" default="true"/>
    </localizations>

    <default-templates>
        <default-template type="page">homepage</default-template>
        <default-template type="home">homepage</default-template>
    </default-templates>

    <templates>
        <template type="search">search/search</template>
        <template type="error">error/error</template>
    </templates>

    <excluded-templates>
        <excluded-template>example</excluded-template>
    </excluded-templates>

    <navigation>
        <contexts>
            <context key="main">
                <meta>
                    <title lang="en">Main Navigation</title>
                    <title lang="de">Hauptnavigation</title>
                </meta>
            </context>
        </contexts>
    </navigation>

    <portals>
        <portal>
            <name>Sulu Blog</name>
            <key>sulu-blog</key>

            <environments>
                <environment type="prod">
                    <urls>
                        <url language="en">{host}/blog</url>
                    </urls>
                </environment>
                <environment type="stage">
                    <urls>
                        <url language="en">{host}/blog</url>
                    </urls>
                </environment>
                <environment type="test">
                    <urls>
                        <url language="en">{host}/blog</url>
                    </urls>
                </environment>
                <environment type="dev">
                    <urls>
                        <url language="en">{host}/blog</url>
                    </urls>
                    <custom-urls>
                        <custom-url>localhost/*</custom-url>
                    </custom-urls>
                </environment>
            </environments>
        </portal>
    </portals>
</webspace>

=== sulu/sulu/config/webspaces/sulu-test.xml
<?xml version="1.0" encoding="utf-8"?>
<webspace xmlns="http://schemas.sulu.io/webspace/webspace"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/webspace/webspace http://schemas.sulu.io/webspace/webspace-1.1.xsd">

    <name>Sulu Test</name>
    <key>sulu-test</key>

    <localizations>
        <localization language="en" default="true"/>
    </localizations>

    <default-templates>
        <default-template type="pages">default</default-template>
        <default-template type="home">homepage</default-template>
    </default-templates>

    <templates>
        <template type="search">templates/search.html.twig</template>
        <template type="error">templates/error.html.twig</template>
    </templates>

    <navigation>
        <contexts>
            <context key="main">
                <meta>
                    <title lang="en">Main Navigation</title>
                    <title lang="de">Hauptnavigation</title>
                </meta>
            </context>
        </contexts>
    </navigation>

    <portals>
        <portal>
            <name>example.com</name>
            <key>example</key>

            <environments>
                <environment type="prod">
                    <urls>
                        <url language="en">{host}</url>
                    </urls>
                </environment>
                <environment type="stage">
                    <urls>
                        <url language="en">{host}</url>
                    </urls>
                </environment>
                <environment type="test">
                    <urls>
                        <url language="en">{host}</url>
                    </urls>
                </environment>
                <environment type="dev">
                    <urls>
                        <url language="en">{host}</url>
                    </urls>
                </environment>
            </environments>
        </portal>
    </portals>
</webspace>
