=== sulu/sulu/src/Sulu/Component/Content/Metadata/Loader/schema/template-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           targetNamespace="http://schemas.sulu.io/template/template"
           xmlns="http://schemas.sulu.io/template/template"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!--
    Import XML namespace (used by xincludes)
    -->
    <xs:import namespace='http://www.w3.org/XML/1998/namespace' schemaLocation='xml.xsd'/>

    <!--
    Attribute group for attributes that are allowed for all elements
    -->
    <xs:attributeGroup name="defaultAttributes">
        <xs:anyAttribute namespace='http://www.w3.org/XML/1998/namespace'/>
    </xs:attributeGroup>

    <xs:element name="template" type="templateType"/>
    <xs:element name="properties" type="rootPropertiesType"/>

    <xs:complexType name="templateType">
        <xs:choice maxOccurs="unbounded">
            <xs:element type="xs:string" name="key" minOccurs="1" maxOccurs="1"/>
            <xs:element type="indexType" name="index" minOccurs="1" maxOccurs="1"/>
            <xs:element type="tagType" name="tag" maxOccurs="unbounded"/>
            <xs:element type="xs:string" name="view" minOccurs="1" maxOccurs="1"/>
            <xs:element type="xs:string" name="controller" minOccurs="1" maxOccurs="1"/>
            <xs:element type="xs:string" name="internal" minOccurs="0" maxOccurs="1"/>
            <xs:element type="cacheLifetimeType" name="cacheLifetime" minOccurs="1" maxOccurs="1"/>
            <xs:element type="rootPropertiesType" name="properties" minOccurs="1" maxOccurs="1"/>

            <xs:element name="meta">
                <xs:complexType>
                    <xs:choice maxOccurs="unbounded">
                        <xs:element type="langType" name="title"/>
                    </xs:choice>
                    <xs:attributeGroup ref="defaultAttributes"/>
                </xs:complexType>
            </xs:element>
        </xs:choice>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="metaType">
        <xs:choice maxOccurs="unbounded">
            <xs:element type="langType" name="title"/>
            <xs:element type="langType" name="info_text"/>
            <xs:element type="langType" name="placeholder"/>
        </xs:choice>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="langType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="lang" use="required" type="xs:string"/>
                <xs:attributeGroup ref="defaultAttributes"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="rootPropertiesType">
        <xs:choice minOccurs="1" maxOccurs="unbounded">
            <xs:element type="propertyType" name="property" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element type="blockType" name="block" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element type="sectionType" name="section" minOccurs="0" maxOccurs="unbounded"/>
        </xs:choice>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="sectionType">
        <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element type="metaType" name="meta" minOccurs="0" maxOccurs="1"/>
            <xs:element type="propertiesType" name="properties" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>

        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="cssClass" use="optional"/>
        <xs:attribute type="xs:integer" name="colspan" use="optional"/>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="propertiesType">
        <xs:choice minOccurs="1" maxOccurs="unbounded">
            <xs:element type="propertyType" name="property"/>
            <xs:element type="blockType" name="block"/>
        </xs:choice>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="propertyType" mixed="true">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element type="metaType" name="meta" minOccurs="0" maxOccurs="1"/>
            <xs:element type="tagType" name="tag" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element type="paramsType" name="params" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="indexField" minOccurs="0" maxOccurs="1"/>
        </xs:choice>

        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="type" use="required"/>
        <xs:attribute type="xs:string" name="mandatory" use="optional"/>
        <xs:attribute type="xs:string" name="multilingual" use="optional"/>
        <xs:attribute type="xs:nonNegativeInteger" name="minOccurs" use="optional"/>
        <xs:attribute type="xs:positiveInteger" name="maxOccurs" use="optional"/>
        <xs:attribute type="xs:string" name="cssClass" use="optional"/>
        <xs:attribute type="xs:integer" name="colspan" use="optional"/>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="blockType">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element type="metaType" name="meta" minOccurs="0" maxOccurs="1"/>
            <xs:element type="tagType" name="tag" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element type="blockTypesType" name="types" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>

        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="default-type" use="required"/>
        <xs:attribute type="xs:string" name="mandatory" use="optional"/>
        <xs:attribute type="xs:string" name="multilingual" use="optional"/>
        <xs:attribute type="xs:nonNegativeInteger" name="minOccurs" use="optional"/>
        <xs:attribute type="xs:positiveInteger" name="maxOccurs" use="optional"/>
        <xs:attribute type="xs:string" name="cssClass" use="optional"/>
        <xs:attribute type="xs:integer" name="colspan" use="optional"/>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="blockTypesType">
        <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element type="blockTypeType" name="type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="blockTypeType">
        <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element type="metaType" name="meta" minOccurs="0" maxOccurs="1"/>
            <xs:element type="propertiesType" name="properties" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>

        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="tagType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="required"/>
                <xs:attribute type="xs:int" name="priority" use="optional"/>
                <xs:anyAttribute namespace="##any" processContents="lax"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="cacheLifetimeType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="type" default="seconds">
                    <xs:simpleType>
                        <xs:union memberTypes="cacheLifetimeTypeEnum cacheLifetimeTypeAnyString"/>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="cacheLifetimeTypeEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="seconds"/>
            <xs:enumeration value="expression"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="cacheLifetimeTypeAnyString">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9a-zA-Z]*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="paramsType">
        <xs:sequence>
            <xs:element type="paramType" name="param" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="paramType">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="param" type="paramType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="meta" type="metaType" minOccurs="0" maxOccurs="1"/>
        </xs:choice>
        <xs:attribute name="type" type="paramTypeType" default="string"/>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="value" type="xs:string" use="optional"/>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:simpleType name="paramTypeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="collection"/>
            <xs:enumeration value="string"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="indexType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="required"/>
                <xs:attributeGroup ref="defaultAttributes"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== sulu/sulu/tests/Resources/DataFixtures/Page/template_sections.xml
<?xml version="1.0" ?>
<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">

    <key>template_sections</key>

    <view>page.html.twig</view>
    <controller>SuluContentBundle:Default:index</controller>
    <cacheLifetime>2400</cacheLifetime>

    <properties>
        <property name="title" type="text_line" mandatory="true" colspan="6">
            <meta>
                <title lang="de">Titel</title>
                <title lang="en">Title</title>

                <info_text lang="de">Titel-Info-DE</info_text>
                <info_text lang="en">Title-Info-EN</info_text>

                <placeholder lang="de">Platzhalter-Info-DE</placeholder>
                <placeholder lang="en">Placeholder-Info-EN</placeholder>
            </meta>
            <tag name="sulu.node.title" priority="10"/>
        </property>

        <section name="test" cssClass="test">
            <meta>
                <title lang="de">Test-DE</title>
                <title lang="en">Test-EN</title>

                <info_text lang="de">Info-DE</info_text>
                <info_text lang="en">Info-EN</info_text>
            </meta>
            <properties>
                <property name="url" type="resource_locator" mandatory="true" cssClass="test"
                          colspan="6">
                    <tag name="sulu.rlp" priority="1"/>
                </property>
                <property name="article" type="text_area" mandatory="false" colspan="6">
                    <tag name="sulu.node.title" priority="5"/>
                </property>
                <block name="block" default-type="test">
                    <meta>
                        <title lang="de">Block-DE</title>
                        <title lang="en">Block-EN</title>

                        <info_text lang="de">Block-Info-DE</info_text>
                        <info_text lang="en">Block-Info-EN</info_text>
                    </meta>
                    <types>
                        <type name="test">
                            <properties>
                                <property name="name" type="text_line"/>
                            </properties>
                        </type>
                    </types>
                </block>
            </properties>
        </section>

        <property name="pages" type="smart_content_selection" mandatory="false">
            <tag name="sulu.node.title"/>
        </property>

        <property name="images" type="image_selection" minOccurs="0" maxOccurs="2" colspan="6">
            <params>
                <param name="minLinks" value="1"/>
                <param name="maxLinks" value="10"/>
            </params>
        </property>
    </properties>
</template>

=== sulu/sulu/tests/Resources/DataFixtures/Page/template_block_type_without_meta.xml
<?xml version="1.0" ?>

<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">

    <key>template_block_types</key>

    <view>ClientWebsiteBundle:Website:complex.html.twig</view>
    <controller>SuluWebsiteBundle:Default:index</controller>
    <cacheLifetime>4800</cacheLifetime>

    <properties>
        <property name="title" type="text_line" mandatory="true">
            <tag name="sulu.node.title" priority="10"/>
        </property>
        <property name="url" type="resource_locator" mandatory="true">
            <tag name="sulu.rlp" priority="1"/>
        </property>
        <block name="block1" default-type="default" minOccurs="2" maxOccurs="10" mandatory="true">
            <meta>
                <title lang="de">Block1 DE</title>
                <title lang="en">Block1 EN</title>
                <info_text lang="de">Info Block1 DE</info_text>
                <info_text lang="en">Info Block1 EN</info_text>
                <placeholder lang="de">Placeholder Block1 DE</placeholder>
                <placeholder lang="en">Placeholder Block1 EN</placeholder>
            </meta>
            <tag name="sulu.node.block" priority="20"/>
            <tag name="sulu.test.block" priority="1"/>
            <types>
                <type name="default">
                    <properties>
                        <property name="title" type="text_line" mandatory="true"/>
                        <property name="article" type="text_area" mandatory="true" minOccurs="2"/>
                    </properties>
                </type>
            </types>
        </block>
    </properties>
</template>

=== sulu/sulu/src/Sulu/Bundle/SearchBundle/Tests/Resources/app/Resources/templates/default.xml
<?xml version="1.0" ?>

<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">

    <key>default</key>

    <view>ClientWebsiteBundle:templates:default</view>
    <controller>SuluWebsiteBundle:Default:index</controller>
    <cacheLifetime>2400</cacheLifetime>

    <meta>
        <title lang="de">Standard</title>
        <title lang="en">Default</title>
    </meta>

    <properties>
        <property name="title" type="text_line" mandatory="true">
            <meta>
                <title lang="de">Titel</title>
                <title lang="en">Title</title>
            </meta>

            <tag name="sulu.search.field" type="string" role="title" />

            <tag name="sulu.rlp.part"/>
        </property>

        <property name="url" type="resource_locator" mandatory="true">
            <meta>
                <title lang="de">Adresse</title>
                <title lang="en">Resourcelocator</title>
            </meta>

            <indexField />

            <tag name="sulu.rlp"/>
        </property>

        <section name="content">
            <meta>
                <title lang="de">Inhalt</title>
                <title lang="en">Content</title>

                <info_text lang="de">Bereich f√ºr den Inhalt</info_text>
                <info_text lang="en">Content Section</info_text>
            </meta>
            <properties>
                <property name="article" type="text_editor">
                    <tag name="sulu.search.field" type="string" role="description"/>
                    <meta>
                        <title lang="de">Artikel</title>
                        <title lang="en">Article</title>
                    </meta>

                    <indexField />

                    <params>
                        <param name="godMode" value="true"/>
                        <param name="links" value="true"/>
                        <param name="tables" value="true"/>
                    </params>
                </property>
            </properties>
        </section>
    </properties>
</template>

=== sulu/sulu/src/Sulu/Bundle/EventLogBundle/Tests/Application/config/templates/pages/default.xml
<?xml version="1.0" ?>
<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">

    <key>default</key>

    <view>pages/default</view>
    <controller>Sulu\Bundle\WebsiteBundle\Controller\DefaultController::indexAction</controller>
    <cacheLifetime>604800</cacheLifetime>

    <meta>
        <title lang="en">Default</title>
        <title lang="de">Standard</title>
    </meta>

    <properties>
        <property name="title" type="text_line" mandatory="true">
            <meta>
                <title lang="en">Title</title>
                <title lang="de">Titel</title>
            </meta>
            <params>
                <param name="headline" value="true"/>
            </params>

            <tag name="sulu.rlp.part"/>
        </property>

        <property name="url" type="resource_locator" mandatory="true">
            <meta>
                <title lang="en">Resourcelocator</title>
                <title lang="de">Adresse</title>
            </meta>

            <tag name="sulu.rlp"/>
        </property>

        <property name="article" type="text_editor">
            <meta>
                <title lang="en">Article</title>
                <title lang="de">Artikel</title>
            </meta>
        </property>
    </properties>
</template>

=== sulu/sulu/tests/Resources/DataFixtures/Page/template_nesting_params.xml
<?xml version="1.0" ?>
<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">

    <key>template_nesting_params</key>

    <view>page.html.twig</view>
    <controller>SuluContentBundle:Default:index</controller>
    <cacheLifetime>2400</cacheLifetime>

    <properties>
        <property name="title" type="text_line" mandatory="true">
            <params>
                <param name="minLinks" value="1"/>
                <param name="maxLinks" value="10"/>
                <param name="test" type="collection">
                    <param name="t1" value="v1"/>
                    <param name="t2" value="v2"/>
                    <param name="t3" value="v3"/>
                    <param name="t4" value="v4"/>
                </param>
            </params>
        </property>

        <property name="url" type="resource_locator" mandatory="true">
            <tag name="sulu.rlp" priority="1"/>
        </property>
    </properties>
</template>

=== sulu/sulu/tests/Resources/DataFixtures/Page/template_missing_mandatory.xml
<?xml version="1.0" ?>

<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">

    <key>template</key>

    <cacheLifetime>2400</cacheLifetime>

    <properties>
        <property name="title" type="textLine" mandatory="true"/>
        <property name="url" type="resourceLocator" mandatory="true">
            <tag name="sulu.rlp" />
        </property>
        <property name="article" type="textArea" mandatory="false"/>
        <property name="pages" type="smartContentSelection" mandatory="false"/>

        <property name="images" type="imageSelection" minOccurs="0" maxOccurs="2">
            <params>
                <param name="minLinks" value="1"/>
                <param name="maxLinks" value="10"/>
            </params>
        </property>
    </properties>
</template>

=== sulu/sulu/config/templates/pages/homepage.xml
<?xml version="1.0" ?>
<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">

    <key>homepage</key>

    <view>templates/pages/homepage</view>
    <controller>SuluWebsiteBundle:Default:index</controller>
    <cacheLifetime>86400</cacheLifetime>

    <meta>
        <title lang="en">Homepage</title>
        <title lang="de">Startseite</title>
    </meta>

    <properties>
        <section name="highlight">
            <properties>
                <property name="title" type="text_line" mandatory="true">
                    <meta>
                        <title lang="en">Title</title>
                        <title lang="de">Titel</title>
                    </meta>
                    <params>
                        <param name="headline" value="true"/>
                    </params>

                    <tag name="sulu.rlp.part"/>
                </property>

                <property name="url" type="resource_locator" mandatory="true">
                    <meta>
                        <title lang="en">Resourcelocator</title>
                        <title lang="de">Adresse</title>
                    </meta>

                    <tag name="sulu.rlp"/>
                </property>
            </properties>
        </section>

        <property name="article" type="text_editor">
            <meta>
                <title lang="en">Article</title>
                <title lang="de">Artikel</title>
            </meta>
        </property>
    </properties>
</template>

=== sulu/sulu/tests/Application/app/Resources/templates/snippets/default.xml
<?xml version="1.0" ?>
<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">

    <key>default</key>

    <meta>
        <title lang="en">Default</title>
        <title lang="de">Standard</title>
    </meta>

    <properties>
        <property name="title" type="text_line" mandatory="true">
            <meta>
                <title lang="en">Title</title>
                <title lang="de">Titel</title>
            </meta>

            <tag name="sulu.node.name"/>
        </property>

        <property name="description" type="text_editor">
            <meta>
                <title lang="en">Description</title>
                <title lang="de">Beschreibung</title>
            </meta>
        </property>

        <property name="media" type="media_selection"/>

        <block name="blocks" default-type="default">
            <types>
                <type name="default">
                    <properties>
                        <property name="text" type="text_line">
                            <meta>
                                <title lang="en">Title</title>
                                <title lang="de">Titel</title>
                            </meta>
                        </property>
                    </properties>
                </type>
                <type name="image">
                    <properties>
                        <property name="image" type="media_selection"/>
                    </properties>
                </type>
            </types>
        </block>

    </properties>
</template>
