=== sulu/sulu/src/Sulu/Component/Content/Metadata/Loader/schema/template-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           targetNamespace="http://schemas.sulu.io/template/template"
           xmlns="http://schemas.sulu.io/template/template"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!--
    Import XML namespace (used by xincludes)
    -->
    <xs:import namespace='http://www.w3.org/XML/1998/namespace' schemaLocation='xml.xsd'/>

    <!--
    Attribute group for attributes that are allowed for all elements
    -->
    <xs:attributeGroup name="defaultAttributes">
        <xs:anyAttribute namespace='http://www.w3.org/XML/1998/namespace'/>
    </xs:attributeGroup>

    <xs:element name="template" type="templateType"/>
    <xs:element name="properties" type="rootPropertiesType"/>

    <xs:complexType name="templateType">
        <xs:choice maxOccurs="unbounded">
            <xs:element type="xs:string" name="key" minOccurs="1" maxOccurs="1"/>
            <xs:element type="indexType" name="index" minOccurs="1" maxOccurs="1"/>
            <xs:element type="tagType" name="tag" maxOccurs="unbounded"/>
            <xs:element type="xs:string" name="view" minOccurs="1" maxOccurs="1"/>
            <xs:element type="xs:string" name="controller" minOccurs="1" maxOccurs="1"/>
            <xs:element type="xs:string" name="internal" minOccurs="0" maxOccurs="1"/>
            <xs:element type="cacheLifetimeType" name="cacheLifetime" minOccurs="1" maxOccurs="1"/>
            <xs:element type="rootPropertiesType" name="properties" minOccurs="1" maxOccurs="1"/>

            <xs:element name="meta">
                <xs:complexType>
                    <xs:choice maxOccurs="unbounded">
                        <xs:element type="langType" name="title"/>
                    </xs:choice>
                    <xs:attributeGroup ref="defaultAttributes"/>
                </xs:complexType>
            </xs:element>
        </xs:choice>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="metaType">
        <xs:choice maxOccurs="unbounded">
            <xs:element type="langType" name="title"/>
            <xs:element type="langType" name="info_text"/>
            <xs:element type="langType" name="placeholder"/>
        </xs:choice>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="langType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="lang" use="required" type="xs:string"/>
                <xs:attributeGroup ref="defaultAttributes"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="rootPropertiesType">
        <xs:choice minOccurs="1" maxOccurs="unbounded">
            <xs:element type="propertyType" name="property" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element type="blockType" name="block" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element type="sectionType" name="section" minOccurs="0" maxOccurs="unbounded"/>
        </xs:choice>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="sectionType">
        <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element type="metaType" name="meta" minOccurs="0" maxOccurs="1"/>
            <xs:element type="propertiesType" name="properties" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>

        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="cssClass" use="optional"/>
        <xs:attribute type="xs:integer" name="colspan" use="optional"/>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="propertiesType">
        <xs:choice minOccurs="1" maxOccurs="unbounded">
            <xs:element type="propertyType" name="property"/>
            <xs:element type="blockType" name="block"/>
        </xs:choice>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="propertyType" mixed="true">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element type="metaType" name="meta" minOccurs="0" maxOccurs="1"/>
            <xs:element type="tagType" name="tag" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element type="paramsType" name="params" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="indexField" minOccurs="0" maxOccurs="1"/>
        </xs:choice>

        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="type" use="required"/>
        <xs:attribute type="xs:string" name="mandatory" use="optional"/>
        <xs:attribute type="xs:string" name="multilingual" use="optional"/>
        <xs:attribute type="xs:nonNegativeInteger" name="minOccurs" use="optional"/>
        <xs:attribute type="xs:positiveInteger" name="maxOccurs" use="optional"/>
        <xs:attribute type="xs:string" name="cssClass" use="optional"/>
        <xs:attribute type="xs:integer" name="colspan" use="optional"/>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="blockType">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element type="metaType" name="meta" minOccurs="0" maxOccurs="1"/>
            <xs:element type="tagType" name="tag" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element type="blockTypesType" name="types" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>

        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="default-type" use="required"/>
        <xs:attribute type="xs:string" name="mandatory" use="optional"/>
        <xs:attribute type="xs:string" name="multilingual" use="optional"/>
        <xs:attribute type="xs:nonNegativeInteger" name="minOccurs" use="optional"/>
        <xs:attribute type="xs:positiveInteger" name="maxOccurs" use="optional"/>
        <xs:attribute type="xs:string" name="cssClass" use="optional"/>
        <xs:attribute type="xs:integer" name="colspan" use="optional"/>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="blockTypesType">
        <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element type="blockTypeType" name="type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="blockTypeType">
        <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element type="metaType" name="meta" minOccurs="0" maxOccurs="1"/>
            <xs:element type="propertiesType" name="properties" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>

        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="tagType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="required"/>
                <xs:attribute type="xs:int" name="priority" use="optional"/>
                <xs:anyAttribute namespace="##any" processContents="lax"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="cacheLifetimeType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="type" default="seconds">
                    <xs:simpleType>
                        <xs:union memberTypes="cacheLifetimeTypeEnum cacheLifetimeTypeAnyString"/>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="cacheLifetimeTypeEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="seconds"/>
            <xs:enumeration value="expression"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="cacheLifetimeTypeAnyString">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9a-zA-Z]*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="paramsType">
        <xs:sequence>
            <xs:element type="paramType" name="param" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="paramType">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="param" type="paramType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="meta" type="metaType" minOccurs="0" maxOccurs="1"/>
        </xs:choice>
        <xs:attribute name="type" type="paramTypeType" default="string"/>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="value" type="xs:string" use="optional"/>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:simpleType name="paramTypeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="collection"/>
            <xs:enumeration value="string"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="indexType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="required"/>
                <xs:attributeGroup ref="defaultAttributes"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== sulu/sulu/src/Sulu/Bundle/AdminBundle/Tests/Application/config/templates/blocks/text_block3.xml
<?xml version="1.0" ?>
<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">

    <key>text_block3</key>

    <meta>
        <title lang="en">Text Block 3</title>
        <title lang="de">Text Block 3</title>
    </meta>

    <properties>
        <property name="title" type="text_line" mandatory="true">
            <meta>
                <title lang="en">Title</title>
                <title lang="de">Titel</title>
            </meta>

        </property>

        <property name="description" type="text_editor">
            <meta>
                <title lang="en">Description</title>
                <title lang="de">Beschreibung</title>
            </meta>
        </property>
    </properties>
</template>

=== sulu/sulu/src/Sulu/Bundle/ContentBundle/Content/templates/excerpt.xml
<?xml version="1.0" ?>

<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">

    <key>excerpt</key>

    <view>not in use</view>
    <controller>not in use</controller>
    <cacheLifetime>1</cacheLifetime>

    <properties>
        <property name="title" type="text_line">
            <meta>
                <title lang="de">Titel</title>
                <title lang="en">Title</title>
            </meta>
        </property>

        <property name="more" type="text_line">
            <meta>
                <title lang="de">Text für weiterführenden Link</title>
                <title lang="en">Text for more link</title>
            </meta>
        </property>

        <property name="description" type="text_editor">
            <meta>
                <title lang="de">Beschreibung</title>
                <title lang="en">Description</title>
            </meta>
        </property>

        <property name="categories" type="category_list">
            <meta>
                <title lang="de">Kategorien</title>
                <title lang="en">Categories</title>
            </meta>
        </property>

        <property name="tags" type="tag_list">
            <meta>
                <title lang="de">Tags</title>
                <title lang="en">Tags</title>
            </meta>
        </property>

        <property name="icon" type="media_selection">
            <meta>
                <title lang="de">Icon</title>
                <title lang="en">Icon</title>
            </meta>
        </property>

        <property name="images" type="media_selection">
            <meta>
                <title lang="de">Bilder</title>
                <title lang="en">Images</title>
            </meta>
        </property>
    </properties>
</template>
