=== sulu/sulu/src/Sulu/Bundle/MediaBundle/Media/FormatLoader/schema/formats/formats-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           targetNamespace="http://schemas.sulu.io/media/formats" xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://schemas.sulu.io/media/formats">

    <xs:complexType name="formatsType">
        <xs:sequence>
            <xs:element type="formatType" name="format" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="formatType">
        <xs:sequence>
            <xs:element type="xs:string" name="name"/>

            <xs:element type="commandsType" name="commands" minOccurs="0" maxOccurs="1"/>
            <xs:element type="optionsType" name="options" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="commandsType">
        <xs:sequence>
            <xs:element type="commandType" name="command" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="commandType">
        <xs:sequence>
            <xs:element type="xs:string" name="action"/>
            <xs:element type="parametersType" name="parameters"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="parametersType">
        <xs:sequence>
            <xs:element type="parameterType" name="parameter" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="optionsType">
        <xs:sequence>
            <xs:element type="parameterType" name="option" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="parameterType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:element name="formats" type="formatsType"/>
</xs:schema>

=== sulu/sulu/src/Sulu/Bundle/MediaBundle/Resources/config/image-formats.xml
<?xml version="1.0" encoding="UTF-8"?>
<formats xmlns="http://schemas.sulu.io/media/formats"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://schemas.sulu.io/media/formats http://schemas.sulu.io/media/formats-1.0.xsd">
    <format>
        <name>400x400</name>
        <commands>
            <command>
                <action>scale</action>
                <parameters>
                    <parameter name="x">400</parameter>
                    <parameter name="y">400</parameter>
                </parameters>
            </command>
        </commands>
    </format>
    <format>
        <name>400x400-inset</name>
        <commands>
            <command>
                <action>scale</action>
                <parameters>
                    <parameter name="x">400</parameter>
                    <parameter name="y">400</parameter>
                    <parameter name="mode">inset</parameter>
                </parameters>
            </command>
        </commands>
    </format>
    <format>
        <name>200x200</name>
        <commands>
            <command>
                <action>scale</action>
                <parameters>
                    <parameter name="x">200</parameter>
                    <parameter name="y">200</parameter>
                </parameters>
            </command>
        </commands>
    </format>
    <format>
        <name>190x</name>
        <commands>
            <command>
                <action>scale</action>
                <parameters>
                    <parameter name="x">190</parameter>
                </parameters>
            </command>
        </commands>
    </format>
    <format>
        <name>170x170</name>
        <commands>
            <command>
                <action>scale</action>
                <parameters>
                    <parameter name="x">170</parameter>
                    <parameter name="y">170</parameter>
                </parameters>
            </command>
        </commands>
    </format>
    <format>
        <name>150x100</name>
        <commands>
            <command>
                <action>scale</action>
                <parameters>
                    <parameter name="x">150</parameter>
                    <parameter name="y">100</parameter>
                </parameters>
            </command>
        </commands>
    </format>
    <format>
        <name>100x100</name>
        <commands>
            <command>
                <action>scale</action>
                <parameters>
                    <parameter name="x">100</parameter>
                    <parameter name="y">100</parameter>
                </parameters>
            </command>
        </commands>
    </format>
    <format>
        <name>100x100-inset</name>
        <commands>
            <command>
                <action>scale</action>
                <parameters>
                    <parameter name="x">100</parameter>
                    <parameter name="y">100</parameter>
                    <parameter name="mode">inset</parameter>
                </parameters>
            </command>
        </commands>
    </format>
    <format>
        <name>50x50</name>
        <commands>
            <command>
                <action>scale</action>
                <parameters>
                    <parameter name="x">50</parameter>
                    <parameter name="y">50</parameter>
                </parameters>
            </command>
        </commands>
    </format>
</formats>
